#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /lucky/number
  controller: App\Controller\MyController::number

api_show_message:
  path: /api/all
  controller: App\Controller\MyController::show_all

json-rpc-endpoint:
  resource: '@JsonRpcHttpServerBundle/Resources/config/routing/endpoint.xml'
