#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /lucky/number
  controller: App\Controller\MyController::number

api_show_message:
  path: /api/all
  controller: App\Controller\MyController::show_all

mypage:
  path: /mypage
  controller: App\Controller\MyController::mypage

create_user:
  path: /create_user
  controller: App\Controller\UserController::create_user

user:
  path: /user
  controller: App\Controller\UserController::index

json-rpc-endpoint:
  resource: '@JsonRpcHttpServerBundle/Resources/config/routing/endpoint.xml'
