name: CI

on: [push]

env:
  DEPLOY_PATH: /var/www/project_prod
  BUILD_SCRIPT: npm run build
  BUILD_SCRIPT_OUTPUT: dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Записываем в переменные окружения имя текущей ветки
      # Чтобы избежать конфиликтов с URL, меняем точки на _, а слеши на минусы
      - name: Get branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g' | sed 's/\./_/g')"
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_PATH }}/${{ env.BRANCH_NAME }}
          strip_components: 1
      - name: Print Info
        run: echo "Deployed!"
